package com.vs.vsadmin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vs.springhelper.SpringContextHelper;

public class MainGUI extends CustomComponent {


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Button saveAttributesButton;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	
	private MainMenuGen mainMenuGen;
	private SubMenuGen subMenuGen;
	private SubMenuCatagorizationGen subMenuCatagorizationGen;
	private VSAttributeUiGen vsAttributeUiGen;
	AttributesAssinerUIGen attributeAssignerUIGen;
	public void setVsAttributeUiGen(VSAttributeUiGen vsAttributeUiGen) {
		this.vsAttributeUiGen = vsAttributeUiGen;
	}

	public void setSubMenuGen(SubMenuGen subMenuGen) {
		this.subMenuGen = subMenuGen;
	}

	public void setMainMenuGen(MainMenuGen mainMenuGen) {
		this.mainMenuGen = mainMenuGen;
	}

	public void setSubMenuCatagorizationGen(
			SubMenuCatagorizationGen subMenuCatagorizationGen) {
		this.subMenuCatagorizationGen = subMenuCatagorizationGen;
	}



	public void setAttributeAssignerUIGen(
			AttributesAssinerUIGen attributeAssignerUIGen) {
		this.attributeAssignerUIGen = attributeAssignerUIGen;
	}

	public MainGUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		verticalLayout_3.setSpacing(true);
		mainLayout.addComponent(verticalLayout_3);
		mainLayout.setExpandRatio(verticalLayout_3, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		verticalLayout_2.setSpacing(true);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Main Menu Generator");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		button_1.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				 SpringContextHelper helper = new SpringContextHelper(VaadinServlet.getCurrent().getServletContext());
				MainMenuGen mainMenuGen = (MainMenuGen) helper.getBean("mainMenuGen");
				verticalLayout_3.removeAllComponents();
				verticalLayout_3.addComponent(mainMenuGen);
			}
		});
		verticalLayout_2.addComponent(button_1);
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Sub Menu Generator");
		button_2.setImmediate(false);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		
		button_2.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				verticalLayout_3.removeAllComponents();
				SpringContextHelper helper = new SpringContextHelper(VaadinServlet.getCurrent().getServletContext());
				SubMenuGen subMenuGen = (SubMenuGen) helper.getBean("subMenuGen");
				subMenuGen.setUpdatedMainMenusInComponent();
				verticalLayout_3.addComponent(subMenuGen);
			}
		});
		verticalLayout_2.addComponent(button_2);
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Save Sub Menu Catogorization");
		button_3.setImmediate(false);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		button_3.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				verticalLayout_3.removeAllComponents();
				SpringContextHelper helper = new SpringContextHelper(VaadinServlet.getCurrent().getServletContext());
				SubMenuCatagorizationGen subMenuCatagorizationGen = (SubMenuCatagorizationGen) helper.getBean("subMenuCatagorizationGen");
				subMenuCatagorizationGen.setUpdatedSubMenusInComponent();
				verticalLayout_3.addComponent(subMenuCatagorizationGen);
			}
		});
		verticalLayout_2.addComponent(button_3);
		
		// saveAttributesButton
		saveAttributesButton = new Button();
		saveAttributesButton.setCaption("SaveAttributes");
		saveAttributesButton.setImmediate(false);
		saveAttributesButton.setWidth("-1px");
		saveAttributesButton.setHeight("-1px");
		verticalLayout_2.addComponent(saveAttributesButton);
		saveAttributesButton.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				verticalLayout_3.removeAllComponents();
				SpringContextHelper helper = new SpringContextHelper(VaadinServlet.getCurrent().getServletContext());
				VSAttributeUiGen vsAttributeUiGen = (VSAttributeUiGen) helper.getBean("attributeUIGen");
				verticalLayout_3.addComponent(vsAttributeUiGen);
			}
		});
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("Add Attributes to Menus");
		button_5.setImmediate(false);
		button_5.setWidth("-1px");
		button_5.setHeight("-1px");
		verticalLayout_2.addComponent(button_5);
		verticalLayout_2.setExpandRatio(button_5, 1.0f);
		button_5.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				verticalLayout_3.removeAllComponents();
				SpringContextHelper helper = new SpringContextHelper(VaadinServlet.getCurrent().getServletContext());
				AttributesAssinerUIGen attributesAssinerUIGen = (AttributesAssinerUIGen) helper.getBean("attributeAssignerUIGen");
				attributesAssinerUIGen.setUpdatedMenusInComponent();
				verticalLayout_3.addComponent(attributesAssinerUIGen);
			}
		});
		
		return verticalLayout_2;
	}
}
