package com.vs.vsadmin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.MouseEvents;
import com.vaadin.event.MouseEvents.ClickEvent;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class Sim extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Sim() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(true);
		table_1.addContainerProperty("val", String.class, "");
		table_1.addContainerProperty("", Image.class,null);
		
		for(int i=0;i<10;i++){
			Image image = new Image();
			image.setImmediate(true);
			image.setSource(new ThemeResource("images/close.ico"));
			Integer integer = i;
			image.addClickListener(new MouseEvents.ClickListener() {
				@Override
				public void click(ClickEvent event) {
					System.out.println(event.getComponent().getId());
					Image object = (Image) event.getComponent();
					table_1.removeItem(object.getData());
				}
			});
			Object object = table_1.addItem(new Object[]{integer.toString(),image},i);
			image.setData(object);
		}
		table_1.setSelectable(true);
		mainLayout.addComponent(table_1);
		
		return mainLayout;
	}

}
